apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-data
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/dev/volumes/elastic-data/"
    type: DirectoryOrCreate
